export const words = [
  { word: "행복", meaning: "생활에서 충분한 만족과 기쁨을 느끼는 상태" },
  { word: "모순", meaning: "말이나 행동의 앞뒤가 서로 맞지 않음" },
  { word: "자전거", meaning: "두 바퀴로 달리는 이동 수단" },
  { word: "사과", meaning: "잘못을 인정하고 용서를 비는 일" },
  { word: "바다", meaning: "넓고 큰 물의 공간" },
  { word: "하늘", meaning: "지구를 둘러싼 공간" },
  { word: "친구", meaning: "서로 친하게 지내는 사람" },
  { word: "가족", meaning: "혈연이나 혼인으로 맺어진 공동체" },
  { word: "학교", meaning: "교육을 받는 기관" },
  { word: "책상", meaning: "공부나 일을 할 때 사용하는 가구" },

  { word: "의자", meaning: "앉기 위해 사용하는 가구" },
  { word: "음악", meaning: "소리를 조합해 만든 예술" },
  { word: "영화", meaning: "영상으로 이야기를 전달하는 작품" },
  { word: "시간", meaning: "흐름과 변화를 나타내는 개념" },
  { word: "공간", meaning: "사물이나 사람이 존재하는 자리" },
  { word: "노력", meaning: "어떤 목표를 위해 힘을 씀" },
  { word: "성공", meaning: "목표를 이루는 것" },
  { word: "실패", meaning: "목표를 이루지 못함" },
  { word: "도전", meaning: "어려운 일에 맞서 시도함" },
  { word: "변화", meaning: "상태나 모습이 달라짐" },

  { word: "발견", meaning: "새로운 것을 찾아냄" },
  { word: "창의", meaning: "새로운 생각을 만들어냄" },
  { word: "집중", meaning: "한 가지에 마음을 모음" },
  { word: "휴식", meaning: "몸과 마음을 쉬게 함" },
  { word: "여행", meaning: "다른 곳으로 이동하며 경험함" },
  { word: "기억", meaning: "경험한 것을 마음에 저장함" },
  { word: "망각", meaning: "기억을 잊어버림" },
  { word: "사랑", meaning: "깊이 아끼고 좋아하는 마음" },
  { word: "미움", meaning: "싫어하고 증오하는 감정" },
  { word: "기쁨", meaning: "즐겁고 만족스러운 감정" },

  { word: "슬픔", meaning: "마음이 아프고 괴로운 감정" },
  { word: "분노", meaning: "화가 나는 감정" },
  { word: "용기", meaning: "두려움을 이겨내는 마음" },
  { word: "희망", meaning: "좋은 일이 일어나길 바람" },
  { word: "절망", meaning: "희망을 잃은 상태" },
  { word: "건강", meaning: "몸과 마음이 튼튼한 상태" },
  { word: "질병", meaning: "몸이 아픈 상태" },
  { word: "운동", meaning: "몸을 단련하기 위한 활동" },
  { word: "식사", meaning: "음식을 먹는 행위" },
  { word: "요리", meaning: "음식을 만드는 일" },

  { word: "과일", meaning: "나무에서 나는 달거나 신 음식" },
  { word: "채소", meaning: "밭에서 재배하는 식물성 음식" },
  { word: "동물", meaning: "움직이며 살아가는 생물" },
  { word: "식물", meaning: "땅에서 자라는 생명체" },
  { word: "자연", meaning: "사람의 손이 닿지 않은 환경" },
  { word: "환경", meaning: "생물이 살아가는 주변 조건" },
  { word: "지구", meaning: "사람이 살고 있는 행성" },
  { word: "태양", meaning: "빛과 열을 내는 별" },
  { word: "달빛", meaning: "달에서 반사되는 빛" },
  { word: "별빛", meaning: "별에서 오는 빛" },

  { word: "비행기", meaning: "하늘을 나는 교통수단" },
  { word: "자동차", meaning: "도로를 달리는 이동 수단" },
  { word: "기차", meaning: "철로 위를 달리는 교통수단" },
  { word: "버스", meaning: "여러 사람이 타는 대중교통" },
  { word: "지하철", meaning: "지하에서 운행하는 열차" },
  { word: "도로", meaning: "차와 사람이 다니는 길" },
  { word: "건물", meaning: "사람이 생활하거나 일하는 구조물" },
  { word: "도시", meaning: "사람과 시설이 밀집된 지역" },
  { word: "마을", meaning: "사람들이 모여 사는 곳" },
  { word: "나라", meaning: "주권을 가진 사회 공동체" },

  { word: "문화", meaning: "사람들이 만들어낸 생활 방식" },
  { word: "예술", meaning: "아름다움을 표현하는 활동" },
  { word: "과학", meaning: "자연 현상을 연구하는 학문" },
  { word: "기술", meaning: "문제를 해결하기 위한 방법" },
  { word: "정보", meaning: "의미 있는 데이터" },
  { word: "지식", meaning: "배워서 알게 된 내용" },
  { word: "학습", meaning: "지식을 배우는 과정" },
  { word: "교육", meaning: "가르치고 배우는 활동" },
  { word: "언어", meaning: "의사소통을 위한 수단" },
  { word: "문장", meaning: "의미를 가진 말의 단위" },

  { word: "단어", meaning: "의미를 가진 가장 작은 말의 단위" },
  { word: "글자", meaning: "소리를 나타내는 기호" },
  { word: "소리", meaning: "귀로 들을 수 있는 진동" },
  { word: "빛", meaning: "눈으로 볼 수 있는 에너지" },
  { word: "그림", meaning: "형상을 표현한 시각적 결과물" },
  { word: "사진", meaning: "카메라로 찍은 이미지" },
  { word: "영상", meaning: "움직이는 이미지" },
  { word: "게임", meaning: "규칙에 따라 즐기는 활동" },
  { word: "놀이", meaning: "즐거움을 위한 활동" },
  { word: "취미", meaning: "즐기기 위해 하는 활동" },

  { word: "직업", meaning: "생계를 위해 하는 일" },
  { word: "회사", meaning: "이익을 위해 운영되는 조직" },
  { word: "업무", meaning: "맡아서 하는 일" },
  { word: "계획", meaning: "앞으로 할 일을 정리함" },
  { word: "목표", meaning: "이루고자 하는 대상" },
  { word: "결과", meaning: "어떤 일의 끝이나 성과" },
  { word: "과정", meaning: "결과에 이르는 단계" },
  { word: "문제", meaning: "해결해야 할 상황" },
  { word: "해결", meaning: "문제를 풀어냄" },
  { word: "선택", meaning: "여러 것 중 하나를 고름" },

  { word: "결정", meaning: "생각을 정하여 확정함" },
  { word: "이해", meaning: "뜻을 알아차림" },
  { word: "설명", meaning: "내용을 알기 쉽게 풀이함" },
  { word: "표현", meaning: "생각이나 감정을 드러냄" },
  { word: "소통", meaning: "서로 뜻을 주고받음" },
  { word: "관계", meaning: "사람이나 사물 사이의 연결" },
  { word: "신뢰", meaning: "믿고 의지하는 마음" },
  { word: "책임", meaning: "맡은 일에 대한 의무" },
  { word: "자유", meaning: "구속받지 않는 상태" },
  { word: "평화", meaning: "갈등 없이 안정된 상태" }
];

export const WORDS = words;
