export const words = [
  { word: "행복", meaning: "생활에서 충분한 만족과 기쁨을 느끼는 상태" },
  { word: "모순", meaning: "말이나 행동의 앞뒤가 서로 맞지 않음" },
  { word: "자전거", meaning: "두 바퀴로 달리는 이동 수단" },
  { word: "사과", meaning: "잘못을 인정하고 용서를 비는 일" },
  { word: "바다", meaning: "넓고 큰 물의 공간" },
  { word: "하늘", meaning: "지구를 둘러싼 공간" },
  { word: "친구", meaning: "서로 친하게 지내는 사람" },
  { word: "가족", meaning: "혈연이나 혼인으로 맺어진 공동체" },
  { word: "학교", meaning: "교육을 받는 기관" },
  { word: "책상", meaning: "공부나 일을 할 때 사용하는 가구" },

  { word: "의자", meaning: "앉기 위해 사용하는 가구" },
  { word: "음악", meaning: "소리를 조합해 만든 예술" },
  { word: "영화", meaning: "영상으로 이야기를 전달하는 작품" },
  { word: "시간", meaning: "흐름과 변화를 나타내는 개념" },
  { word: "공간", meaning: "사물이나 사람이 존재하는 자리" },
  { word: "노력", meaning: "어떤 목표를 위해 힘을 씀" },
  { word: "성공", meaning: "목표를 이루는 것" },
  { word: "실패", meaning: "목표를 이루지 못함" },
  { word: "도전", meaning: "어려운 일에 맞서 시도함" },
  { word: "변화", meaning: "상태나 모습이 달라짐" },

  { word: "발견", meaning: "새로운 것을 찾아냄" },
  { word: "창의", meaning: "새로운 생각을 만들어냄" },
  { word: "집중", meaning: "한 가지에 마음을 모음" },
  { word: "휴식", meaning: "몸과 마음을 쉬게 함" },
  { word: "여행", meaning: "다른 곳으로 이동하며 경험함" },
  { word: "기억", meaning: "경험한 것을 마음에 저장함" },
  { word: "망각", meaning: "기억을 잊어버림" },
  { word: "사랑", meaning: "깊이 아끼고 좋아하는 마음" },
  { word: "미움", meaning: "싫어하고 증오하는 감정" },
  { word: "기쁨", meaning: "즐겁고 만족스러운 감정" },

  { word: "슬픔", meaning: "마음이 아프고 괴로운 감정" },
  { word: "분노", meaning: "화가 나는 감정" },
  { word: "용기", meaning: "두려움을 이겨내는 마음" },
  { word: "희망", meaning: "좋은 일이 일어나길 바람" },
  { word: "절망", meaning: "희망을 잃은 상태" },
  { word: "건강", meaning: "몸과 마음이 튼튼한 상태" },
  { word: "질병", meaning: "몸이 아픈 상태" },
  { word: "운동", meaning: "몸을 단련하기 위한 활동" },
  { word: "식사", meaning: "음식을 먹는 행위" },
  { word: "요리", meaning: "음식을 만드는 일" },

  { word: "과일", meaning: "나무에서 나는 달거나 신 음식" },
  { word: "채소", meaning: "밭에서 재배하는 식물성 음식" },
  { word: "동물", meaning: "움직이며 살아가는 생물" },
  { word: "식물", meaning: "땅에서 자라는 생명체" },
  { word: "자연", meaning: "사람의 손이 닿지 않은 환경" },
  { word: "환경", meaning: "생물이 살아가는 주변 조건" },
  { word: "지구", meaning: "사람이 살고 있는 행성" },
  { word: "태양", meaning: "빛과 열을 내는 별" },
  { word: "달빛", meaning: "달에서 반사되는 빛" },
  { word: "별빛", meaning: "별에서 오는 빛" },

  { word: "비행기", meaning: "하늘을 나는 교통수단" },
  { word: "자동차", meaning: "도로를 달리는 이동 수단" },
  { word: "기차", meaning: "철로 위를 달리는 교통수단" },
  { word: "버스", meaning: "여러 사람이 타는 대중교통" },
  { word: "지하철", meaning: "지하에서 운행하는 열차" },
  { word: "도로", meaning: "차와 사람이 다니는 길" },
  { word: "건물", meaning: "사람이 생활하거나 일하는 구조물" },
  { word: "도시", meaning: "사람과 시설이 밀집된 지역" },
  { word: "마을", meaning: "사람들이 모여 사는 곳" },
  { word: "나라", meaning: "주권을 가진 사회 공동체" },

  { word: "문화", meaning: "사람들이 만들어낸 생활 방식" },
  { word: "예술", meaning: "아름다움을 표현하는 활동" },
  { word: "과학", meaning: "자연 현상을 연구하는 학문" },
  { word: "기술", meaning: "문제를 해결하기 위한 방법" },
  { word: "정보", meaning: "의미 있는 데이터" },
  { word: "지식", meaning: "배워서 알게 된 내용" },
  { word: "학습", meaning: "지식을 배우는 과정" },
  { word: "교육", meaning: "가르치고 배우는 활동" },
  { word: "언어", meaning: "의사소통을 위한 수단" },
  { word: "문장", meaning: "의미를 가진 말의 단위" },

  { word: "단어", meaning: "의미를 가진 가장 작은 말의 단위" },
  { word: "글자", meaning: "소리를 나타내는 기호" },
  { word: "소리", meaning: "귀로 들을 수 있는 진동" },
  { word: "빛", meaning: "눈으로 볼 수 있는 에너지" },
  { word: "그림", meaning: "형상을 표현한 시각적 결과물" },
  { word: "사진", meaning: "카메라로 찍은 이미지" },
  { word: "영상", meaning: "움직이는 이미지" },
  { word: "게임", meaning: "규칙에 따라 즐기는 활동" },
  { word: "놀이", meaning: "즐거움을 위한 활동" },
  { word: "취미", meaning: "즐기기 위해 하는 활동" },

  { word: "직업", meaning: "생계를 위해 하는 일" },
  { word: "회사", meaning: "이익을 위해 운영되는 조직" },
  { word: "업무", meaning: "맡아서 하는 일" },
  { word: "계획", meaning: "앞으로 할 일을 정리함" },
  { word: "목표", meaning: "이루고자 하는 대상" },
  { word: "결과", meaning: "어떤 일의 끝이나 성과" },
  { word: "과정", meaning: "결과에 이르는 단계" },
  { word: "문제", meaning: "해결해야 할 상황" },
  { word: "해결", meaning: "문제를 풀어냄" },
  { word: "선택", meaning: "여러 것 중 하나를 고름" },

  { word: "결정", meaning: "생각을 정하여 확정함" },
  { word: "이해", meaning: "뜻을 알아차림" },
  { word: "설명", meaning: "내용을 알기 쉽게 풀이함" },
  { word: "표현", meaning: "생각이나 감정을 드러냄" },
  { word: "소통", meaning: "서로 뜻을 주고받음" },
  { word: "관계", meaning: "사람이나 사물 사이의 연결" },
  { word: "신뢰", meaning: "믿고 의지하는 마음" },
  { word: "책임", meaning: "맡은 일에 대한 의무" },
  { word: "자유", meaning: "구속받지 않는 상태" },
  { word: "평화", meaning: "갈등 없이 안정된 상태" },

  { word: "마음", meaning: "생각이나 감정을 느끼는 내면" },
  { word: "약속", meaning: "앞으로 어떤 일을 하기로 정함" },
  { word: "선물", meaning: "다른 사람에게 주는 물건" },
  { word: "이름", meaning: "사람이나 사물을 부르는 말" },
  { word: "아침", meaning: "하루가 시작되는 이른 시간" },
  { word: "저녁", meaning: "해가 질 무렵의 시간" },
  { word: "바람", meaning: "공기가 움직이는 현상" },
  { word: "구름", meaning: "하늘에 떠 있는 물방울 무리" },
  { word: "눈물", meaning: "눈에서 나는 물" },
  { word: "웃음", meaning: "기쁨을 나타내는 표정이나 소리" },

  { word: "노래", meaning: "가락에 맞추어 부르는 말" },
  { word: "편지", meaning: "소식을 전하기 위해 쓴 글" },
  { word: "시장", meaning: "물건을 사고파는 곳" },
  { word: "가방", meaning: "물건을 넣어 들고 다니는 도구" },
  { word: "신발", meaning: "발에 신는 물건" },
  { word: "창문", meaning: "빛과 공기가 드나드는 문" },
  { word: "거울", meaning: "모습을 비추어 보는 물건" },
  { word: "종이", meaning: "글을 쓰거나 그림을 그리는 얇은 물건" },
  { word: "연필", meaning: "글씨를 쓰거나 그림을 그리는 도구" },
  { word: "공책", meaning: "글씨를 쓰기 위해 묶은 종이" },

  { word: "계절", meaning: "날씨 변화에 따라 나뉘는 시기" },
  { word: "봄날", meaning: "봄철의 하루" },
  { word: "여름", meaning: "봄과 가을 사이의 더운 계절" },
  { word: "가을", meaning: "여름과 겨울 사이의 계절" },
  { word: "겨울", meaning: "가을 다음의 추운 계절" },
  { word: "온도", meaning: "따뜻하고 차가운 정도" },
  { word: "소풍", meaning: "바람을 쐬러 밖으로 나가는 일" },
  { word: "풍경", meaning: "눈앞에 보이는 주변 모습" },
  { word: "그늘", meaning: "빛이 가려져 어두운 곳" },
  { word: "물결", meaning: "물 위에 일어나는 움직임" },

  { word: "감정", meaning: "마음에 일어나는 느낌" },
  { word: "생각", meaning: "머릿속으로 떠올리는 내용" },
  { word: "습관", meaning: "반복되어 익숙해진 행동" },
  { word: "관심", meaning: "어떤 것에 마음이 끌림" },
  { word: "기회", meaning: "어떤 일을 하기에 좋은 때" },
  { word: "경험", meaning: "직접 겪어서 알게 된 일" },
  { word: "질문", meaning: "알고 싶은 것을 물음" },
  { word: "대답", meaning: "물음에 답함" },
  { word: "방법", meaning: "어떤 일을 해내는 길" },
  { word: "이유", meaning: "일이 그렇게 된 까닭" },

  { word: "전화", meaning: "멀리 있는 사람과 말하는 통신 수단" },
  { word: "소식", meaning: "어떤 일의 알려진 내용" },
  { word: "대화", meaning: "서로 말을 주고받음" },
  { word: "인사", meaning: "만나거나 헤어질 때 예를 보임" },
  { word: "표정", meaning: "얼굴에 나타나는 감정의 모습" },
  { word: "목소리", meaning: "사람의 입에서 나는 소리" },
  { word: "발음", meaning: "말소리를 내는 방식" },
  { word: "낱말", meaning: "뜻을 가진 말의 단위" },
  { word: "문법", meaning: "말과 글을 이루는 규칙" },
  { word: "번역", meaning: "다른 언어로 옮김" },

  { word: "가게", meaning: "물건을 파는 작은 곳" },
  { word: "가격", meaning: "물건의 값" },
  { word: "물건", meaning: "쓰임이 있는 대상" },
  { word: "주문", meaning: "필요한 것을 요청함" },
  { word: "영수증", meaning: "돈을 치른 사실을 적은 표" },
  { word: "할인", meaning: "값을 깎아 줌" },
  { word: "계산", meaning: "값이나 수를 셈함" },
  { word: "손님", meaning: "찾아온 사람이나 물건을 사는 사람" },
  { word: "점원", meaning: "가게에서 일하는 사람" },
  { word: "상자", meaning: "물건을 담는 네모난 그릇" },

  { word: "부엌", meaning: "음식을 만드는 공간" },
  { word: "냄비", meaning: "음식을 끓이는 그릇" },
  { word: "접시", meaning: "음식을 담는 넓은 그릇" },
  { word: "숟가락", meaning: "음식을 떠먹는 도구" },
  { word: "젓가락", meaning: "음식을 집어 먹는 두 짝의 도구" },
  { word: "국물", meaning: "국이나 찌개에 있는 물" },
  { word: "반찬", meaning: "밥과 함께 먹는 음식" },
  { word: "김치", meaning: "채소를 양념해 발효시킨 음식" },
  { word: "쌀밥", meaning: "쌀로 지은 밥" },
  { word: "간식", meaning: "끼니 사이에 먹는 음식" },

  { word: "빵집", meaning: "빵을 만들어 파는 곳" },
  { word: "우유", meaning: "젖소의 젖을 가공한 음료" },
  { word: "달걀", meaning: "닭이 낳은 알" },
  { word: "고기", meaning: "먹을 수 있는 동물의 살" },
  { word: "생선", meaning: "먹기 위한 물고기" },
  { word: "두부", meaning: "콩으로 만든 부드러운 음식" },
  { word: "국수", meaning: "밀가루 등으로 길게 만든 음식" },
  { word: "라면", meaning: "기름에 튀겨 말린 국수 음식" },
  { word: "떡볶이", meaning: "떡을 매운 양념에 볶은 음식" },
  { word: "주스", meaning: "과일이나 채소의 즙으로 만든 음료" },

  { word: "사람", meaning: "생각하고 말하며 살아가는 존재" },
  { word: "아이", meaning: "나이가 어린 사람" },
  { word: "어른", meaning: "다 자란 사람" },
  { word: "부모", meaning: "아버지와 어머니" },
  { word: "형제", meaning: "같은 부모에게서 난 남자들" },
  { word: "자매", meaning: "같은 부모에게서 난 여자들" },
  { word: "이웃", meaning: "가까이 사는 사람" },
  { word: "동료", meaning: "같은 일을 함께 하는 사람" },
  { word: "선생", meaning: "가르치는 사람" },
  { word: "학생", meaning: "배우는 사람" },

  { word: "교실", meaning: "수업을 하는 방" },
  { word: "수업", meaning: "가르치고 배우는 시간" },
  { word: "시험", meaning: "실력이나 지식을 평가하는 일" },
  { word: "성적", meaning: "시험이나 일의 결과 점수" },
  { word: "숙제", meaning: "집에서 해 오도록 내는 공부" },
  { word: "칠판", meaning: "글씨를 써서 보여 주는 판" },
  { word: "분필", meaning: "칠판에 쓰는 흰 막대" },
  { word: "가위", meaning: "종이나 천을 자르는 도구" },
  { word: "풀", meaning: "무엇을 붙이는 끈적한 물질" },
  { word: "자", meaning: "길이를 재거나 선을 긋는 도구" },

  { word: "병원", meaning: "아픈 사람을 치료하는 곳" },
  { word: "의사", meaning: "병을 진단하고 치료하는 사람" },
  { word: "약국", meaning: "약을 조제하고 파는 곳" },
  { word: "감기", meaning: "기침과 콧물이 나는 흔한 병" },
  { word: "기침", meaning: "목이나 기관지에서 나는 반응" },
  { word: "콧물", meaning: "코에서 나오는 물" },
  { word: "두통", meaning: "머리가 아픈 증상" },
  { word: "상처", meaning: "몸이 다친 자리" },
  { word: "치료", meaning: "병이나 상처를 낫게 함" },
  { word: "약", meaning: "병을 고치거나 줄이는 물질" },

  { word: "걷기", meaning: "두 발로 천천히 이동함" },
  { word: "달리기", meaning: "빠르게 뛰어 이동함" },
  { word: "수영", meaning: "물속에서 몸을 움직여 나아감" },
  { word: "축구", meaning: "공을 차서 골을 넣는 경기" },
  { word: "야구", meaning: "공을 치고 달리는 경기" },
  { word: "농구", meaning: "공을 골대에 넣는 경기" },
  { word: "배구", meaning: "공을 네트 너머로 넘기는 경기" },
  { word: "탁구", meaning: "작은 공을 탁자 위에서 치는 경기" },
  { word: "등산", meaning: "산에 오르는 활동" },
  { word: "체조", meaning: "몸을 풀고 단련하는 운동" },

  { word: "공원", meaning: "사람들이 쉬거나 산책하는 곳" },
  { word: "놀이터", meaning: "아이들이 놀 수 있는 장소" },
  { word: "벤치", meaning: "여럿이 앉을 수 있는 긴 의자" },
  { word: "나무", meaning: "줄기와 가지가 있는 식물" },
  { word: "꽃", meaning: "식물의 아름다운 생식 기관" },
  { word: "풀잎", meaning: "풀의 잎" },
  { word: "흙", meaning: "땅을 이루는 가는 물질" },
  { word: "돌", meaning: "단단한 광물 덩어리" },
  { word: "모래", meaning: "잘게 부서진 돌 알갱이" },
  { word: "냇물", meaning: "작은 시내에 흐르는 물" },

  { word: "강물", meaning: "강에 흐르는 물" },
  { word: "호수", meaning: "땅 안에 고인 큰 물" },
  { word: "섬", meaning: "물로 둘러싸인 땅" },
  { word: "해변", meaning: "바닷물이 닿는 모래나 땅" },
  { word: "파도", meaning: "바다나 물 위의 큰 물결" },
  { word: "안개", meaning: "땅 가까이에 낀 작은 물방울" },
  { word: "이슬", meaning: "새벽에 맺히는 작은 물방울" },
  { word: "서리", meaning: "추위로 맺힌 흰 얼음 결정" },
  { word: "장마", meaning: "여름철 비가 오래 오는 시기" },
  { word: "무지개", meaning: "비 뒤 하늘에 보이는 여러 빛깔의 띠" },

  { word: "거리", meaning: "사람과 차가 다니는 길" },
  { word: "골목", meaning: "큰길에서 갈라진 좁은 길" },
  { word: "횡단보도", meaning: "사람이 길을 건너는 표시 구역" },
  { word: "신호등", meaning: "빛으로 교통을 알리는 장치" },
  { word: "정류장", meaning: "버스나 차가 멈추는 곳" },
  { word: "승강장", meaning: "기차나 지하철을 타는 곳" },
  { word: "공항", meaning: "비행기가 오가고 사람이 타는 곳" },
  { word: "항구", meaning: "배가 드나드는 곳" },
  { word: "택시", meaning: "돈을 내고 타는 승용차" },
  { word: "자전차", meaning: "사람 힘으로 바퀴를 굴리는 탈것" },

  { word: "방", meaning: "집 안의 칸으로 나뉜 공간" },
  { word: "마루", meaning: "집 안의 넓은 바닥 공간" },
  { word: "현관", meaning: "집이나 건물의 출입구" },
  { word: "욕실", meaning: "몸을 씻는 방" },
  { word: "침대", meaning: "누워 자는 가구" },
  { word: "베개", meaning: "머리를 받치고 자는 물건" },
  { word: "이불", meaning: "몸을 덮고 자는 물건" },
  { word: "옷장", meaning: "옷을 넣어 두는 가구" },
  { word: "서랍", meaning: "물건을 넣고 빼는 칸" },
  { word: "전등", meaning: "전기로 빛을 내는 기구" },

  { word: "시계", meaning: "시간을 알려 주는 물건" },
  { word: "달력", meaning: "날짜와 요일을 적은 표" },
  { word: "열쇠", meaning: "자물쇠를 여는 도구" },
  { word: "문고리", meaning: "문을 여닫을 때 잡는 부분" },
  { word: "수건", meaning: "몸이나 물건의 물기를 닦는 천" },
  { word: "비누", meaning: "몸이나 물건을 씻는 데 쓰는 물질" },
  { word: "칫솔", meaning: "이를 닦는 도구" },
  { word: "치약", meaning: "이를 닦을 때 쓰는 물질" },
  { word: "빗", meaning: "머리카락을 가지런히 하는 도구" },
  { word: "우산", meaning: "비나 햇빛을 막는 물건" },

  { word: "옷", meaning: "몸에 걸치는 물건" },
  { word: "모자", meaning: "머리에 쓰는 물건" },
  { word: "양말", meaning: "발에 신는 천 물건" },
  { word: "장갑", meaning: "손에 끼는 물건" },
  { word: "목도리", meaning: "목에 두르는 긴 천" },
  { word: "외투", meaning: "겉에 걸쳐 입는 옷" },
  { word: "바지", meaning: "두 다리에 꿰어 입는 옷" },
  { word: "치마", meaning: "허리 아래로 둘러 입는 옷" },
  { word: "단추", meaning: "옷을 여미는 작은 물건" },
  { word: "주머니", meaning: "옷이나 가방에 물건을 넣는 부분" },

  { word: "컴퓨터", meaning: "자료를 처리하는 전자 기기" },
  { word: "화면", meaning: "글자나 그림이 보이는 면" },
  { word: "마우스", meaning: "화면의 포인터를 움직이는 장치" },
  { word: "키보드", meaning: "글자와 명령을 입력하는 장치" },
  { word: "인터넷", meaning: "전 세계 컴퓨터를 잇는 통신망" },
  { word: "검색", meaning: "필요한 정보를 찾아봄" },
  { word: "파일", meaning: "컴퓨터에 저장된 자료 묶음" },
  { word: "폴더", meaning: "파일을 담아 정리하는 공간" },
  { word: "암호", meaning: "비밀을 지키기 위한 글자나 숫자" },
  { word: "알림", meaning: "새 소식이나 상태를 알려 줌" },

  { word: "지도", meaning: "땅이나 길을 그려 나타낸 그림" },
  { word: "주소", meaning: "집이나 장소의 위치를 나타낸 말" },
  { word: "방향", meaning: "어떤 쪽을 가리키는 위치" },
  { word: "왼쪽", meaning: "북쪽을 볼 때 서쪽에 해당하는 쪽" },
  { word: "오른쪽", meaning: "북쪽을 볼 때 동쪽에 해당하는 쪽" },
  { word: "앞쪽", meaning: "얼굴이나 시선이 향하는 쪽" },
  { word: "뒤쪽", meaning: "등이 있는 방향의 쪽" },
  { word: "근처", meaning: "멀지 않은 가까운 곳" },
  { word: "중심", meaning: "가운데가 되는 부분" },
  { word: "주변", meaning: "어떤 것의 둘레나 가까운 곳" },

  { word: "색깔", meaning: "물체가 눈에 보이는 빛의 느낌" },
  { word: "빨강", meaning: "피나 불처럼 붉은 색" },
  { word: "노랑", meaning: "개나리꽃 같은 밝은 색" },
  { word: "파랑", meaning: "맑은 하늘이나 바다 같은 색" },
  { word: "초록", meaning: "풀이나 잎처럼 푸른 색" },
  { word: "보라", meaning: "파랑과 빨강이 섞인 듯한 색" },
  { word: "하양", meaning: "눈이나 종이처럼 밝은 색" },
  { word: "검정", meaning: "빛이 거의 없는 어두운 색" },
  { word: "회색", meaning: "검정과 하양이 섞인 색" },
  { word: "분홍", meaning: "연한 빨간빛의 색" },

  { word: "동그라미", meaning: "둥근 모양" },
  { word: "세모", meaning: "세 개의 선으로 된 모양" },
  { word: "네모", meaning: "네 개의 변을 가진 모양" },
  { word: "선", meaning: "길게 이어진 자국이나 줄" },
  { word: "점", meaning: "아주 작은 표시" },
  { word: "면", meaning: "평평하거나 겉으로 보이는 부분" },
  { word: "모양", meaning: "겉으로 보이는 생김새" },
  { word: "크기", meaning: "큰 정도" },
  { word: "길이", meaning: "한쪽 끝에서 다른 끝까지의 거리" },
  { word: "높이", meaning: "아래에서 위까지의 거리" },

  { word: "무게", meaning: "물건이 가진 무거운 정도" },
  { word: "속도", meaning: "움직이는 빠르기" },
  { word: "숫자", meaning: "수를 나타내는 기호" },
  { word: "순서", meaning: "차례대로 놓인 관계" },
  { word: "첫째", meaning: "맨 처음의 차례" },
  { word: "둘째", meaning: "두 번째 차례" },
  { word: "마지막", meaning: "맨 끝의 차례" },
  { word: "전체", meaning: "하나로 묶인 모든 것" },
  { word: "부분", meaning: "전체를 이루는 일부" },
  { word: "절반", meaning: "둘로 나눈 한쪽" },

  { word: "오늘", meaning: "지금 지나고 있는 날" },
  { word: "내일", meaning: "오늘의 다음 날" },
  { word: "어제", meaning: "오늘의 전날" },
  { word: "주말", meaning: "토요일과 일요일 무렵" },
  { word: "평일", meaning: "주말이 아닌 보통 날" },
  { word: "새벽", meaning: "날이 밝기 전 이른 시간" },
  { word: "낮", meaning: "해가 떠 있는 시간" },
  { word: "밤", meaning: "해가 진 뒤의 시간" },
  { word: "순간", meaning: "아주 짧은 시간" },
  { word: "동안", meaning: "어떤 일이 이어지는 시간" },

  { word: "시작", meaning: "일이나 행동을 처음 함" },
  { word: "끝", meaning: "일이나 길이 다한 지점" },
  { word: "준비", meaning: "일을 하기 전에 갖춤" },
  { word: "연습", meaning: "익숙해지도록 되풀이함" },
  { word: "실력", meaning: "실제로 해낼 수 있는 능력" },
  { word: "속마음", meaning: "겉으로 드러나지 않은 마음" },
  { word: "진심", meaning: "거짓 없는 참된 마음" },
  { word: "거짓", meaning: "사실이 아닌 말이나 행동" },
  { word: "비밀", meaning: "남에게 알리지 않는 것" },
  { word: "약점", meaning: "부족하거나 약한 점" },

  { word: "장점", meaning: "좋거나 뛰어난 점" },
  { word: "차이", meaning: "서로 같지 않은 점" },
  { word: "비교", meaning: "둘 이상을 견주어 봄" },
  { word: "기준", meaning: "판단하거나 비교하는 바탕" },
  { word: "규칙", meaning: "지켜야 하는 정해진 질서" },
  { word: "차례", meaning: "순서에 따라 돌아오는 때" },
  { word: "역할", meaning: "맡아서 해야 하는 일" },
  { word: "참여", meaning: "어떤 일에 함께함" },
  { word: "협력", meaning: "힘을 합쳐 도움" },
  { word: "경쟁", meaning: "서로 이기려고 겨룸" },

  { word: "갈등", meaning: "생각이나 이해가 맞서 부딪힘" },
  { word: "화해", meaning: "다툼을 풀고 사이좋게 됨" },
  { word: "배려", meaning: "다른 사람을 생각해 살핌" },
  { word: "존중", meaning: "가치 있게 여기고 소중히 대함" },
  { word: "예의", meaning: "사람 사이에 지키는 바른 태도" },
  { word: "칭찬", meaning: "좋은 점을 말해 줌" },
  { word: "위로", meaning: "힘든 마음을 달래 줌" },
  { word: "격려", meaning: "힘을 내도록 북돋움" },
  { word: "감사", meaning: "고마운 마음을 느낌" },
  { word: "사과문", meaning: "잘못을 인정해 쓴 글" },

  { word: "신문", meaning: "뉴스와 정보를 실은 인쇄물" },
  { word: "기사", meaning: "신문이나 방송의 보도 글" },
  { word: "방송", meaning: "소리나 영상을 널리 보냄" },
  { word: "뉴스", meaning: "새롭게 알려지는 소식" },
  { word: "잡지", meaning: "여러 글과 사진을 모은 책자" },
  { word: "광고", meaning: "상품이나 내용을 널리 알림" },
  { word: "화제", meaning: "이야깃거리가 되는 일" },
  { word: "사건", meaning: "사회적으로 주목할 만한 일" },
  { word: "기록", meaning: "내용을 적어 남김" },
  { word: "자료", meaning: "판단이나 연구에 쓰는 정보" },

  { word: "역사", meaning: "과거에 있었던 일의 흐름" },
  { word: "전통", meaning: "오래 이어져 내려온 문화" },
  { word: "축제", meaning: "기쁜 일을 함께 즐기는 행사" },
  { word: "명절", meaning: "해마다 지키는 특별한 날" },
  { word: "한복", meaning: "한국의 전통 옷" },
  { word: "궁궐", meaning: "임금이 살던 큰 집" },
  { word: "유물", meaning: "옛날 사람이 남긴 물건" },
  { word: "박물관", meaning: "자료와 유물을 모아 전시하는 곳" },
  { word: "전시", meaning: "물건이나 작품을 펼쳐 보임" },
  { word: "공연", meaning: "무대에서 예술을 보여 줌" },

  { word: "무대", meaning: "공연을 하는 자리" },
  { word: "배우", meaning: "극이나 영화에서 연기하는 사람" },
  { word: "가수", meaning: "노래를 부르는 사람" },
  { word: "춤", meaning: "몸을 움직여 표현하는 예술" },
  { word: "악기", meaning: "음악을 연주하는 도구" },
  { word: "피아노", meaning: "건반을 눌러 소리 내는 악기" },
  { word: "기타", meaning: "줄을 튕겨 소리 내는 악기" },
  { word: "북", meaning: "두드려 소리 내는 악기" },
  { word: "리듬", meaning: "소리나 움직임의 규칙적인 흐름" },
  { word: "가락", meaning: "높낮이가 있는 소리의 흐름" },

  { word: "소설", meaning: "꾸며 낸 이야기를 쓴 글" },
  { word: "시", meaning: "느낌과 생각을 짧게 표현한 글" },
  { word: "동화", meaning: "어린이를 위해 쓴 이야기" },
  { word: "만화", meaning: "그림과 글로 엮은 이야기" },
  { word: "작가", meaning: "글이나 작품을 만드는 사람" },
  { word: "독서", meaning: "책을 읽는 일" },
  { word: "도서관", meaning: "책을 모아 두고 빌려 주는 곳" },
  { word: "책장", meaning: "책을 꽂아 두는 가구" },
  { word: "표지", meaning: "책이나 물건의 겉장" },
  { word: "쪽지", meaning: "간단한 내용을 적은 작은 종이" },

  { word: "농장", meaning: "농사를 짓거나 가축을 기르는 곳" },
  { word: "밭", meaning: "채소나 곡식을 기르는 땅" },
  { word: "논", meaning: "벼를 기르는 물 댄 땅" },
  { word: "씨앗", meaning: "식물이 자라나는 작은 알" },
  { word: "뿌리", meaning: "식물이 땅속으로 뻗는 부분" },
  { word: "줄기", meaning: "식물의 몸을 받치는 부분" },
  { word: "잎", meaning: "식물이 빛을 받는 납작한 부분" },
  { word: "열매", meaning: "식물이 맺는 먹을 수 있는 부분" },
  { word: "곡식", meaning: "쌀이나 보리 같은 먹거리 작물" },
  { word: "농부", meaning: "농사를 짓는 사람" },

  { word: "강아지", meaning: "개의 어린 새끼" },
  { word: "고양이", meaning: "작고 부드러운 털을 가진 동물" },
  { word: "새", meaning: "날개와 깃털이 있는 동물" },
  { word: "물고기", meaning: "물속에서 사는 동물" },
  { word: "토끼", meaning: "긴 귀를 가진 작은 동물" },
  { word: "말", meaning: "사람을 태우거나 짐을 나르던 동물" },
  { word: "소", meaning: "농사와 고기에 쓰이는 큰 동물" },
  { word: "돼지", meaning: "고기를 얻기 위해 기르는 동물" },
  { word: "닭", meaning: "알과 고기를 얻기 위해 기르는 새" },
  { word: "벌", meaning: "꽃에서 꿀을 모으는 곤충" },

  { word: "개미", meaning: "무리를 지어 사는 작은 곤충" },
  { word: "나비", meaning: "날개가 넓고 아름다운 곤충" },
  { word: "잠자리", meaning: "긴 몸과 투명한 날개를 가진 곤충" },
  { word: "풀벌레", meaning: "풀숲에 사는 작은 벌레" },
  { word: "동굴", meaning: "땅이나 바위 속의 빈 공간" },
  { word: "숲", meaning: "나무가 많이 자라는 곳" },
  { word: "들판", meaning: "넓게 트인 평평한 땅" },
  { word: "언덕", meaning: "낮고 완만하게 솟은 땅" },
  { word: "절벽", meaning: "깎아지른 듯 높은 바위 벽" },
  { word: "계곡", meaning: "산 사이로 물이 흐르는 골짜기" },

  { word: "세계", meaning: "지구 위의 모든 나라와 사회" },
  { word: "지역", meaning: "일정하게 나뉜 땅이나 범위" },
  { word: "고향", meaning: "태어나거나 자란 곳" },
  { word: "외국", meaning: "자기 나라가 아닌 나라" },
  { word: "국경", meaning: "나라와 나라의 경계" },
  { word: "수도", meaning: "한 나라의 중심 도시" },
  { word: "주민", meaning: "그 지역에 사는 사람" },
  { word: "인구", meaning: "어떤 지역에 사는 사람 수" },
  { word: "지도자", meaning: "사람들을 이끄는 사람" },
  { word: "사회", meaning: "사람들이 모여 살아가는 집단" },

  { word: "경제", meaning: "돈과 물건이 오가는 활동" },
  { word: "은행", meaning: "돈을 맡기고 빌리는 기관" },
  { word: "통장", meaning: "돈의 입출금을 기록한 장부" },
  { word: "동전", meaning: "금속으로 만든 돈" },
  { word: "지폐", meaning: "종이로 만든 돈" },
  { word: "저금", meaning: "돈을 모아 둠" },
  { word: "월급", meaning: "한 달 단위로 받는 돈" },
  { word: "비용", meaning: "무엇을 하는 데 드는 돈" },
  { word: "소비", meaning: "돈이나 물건을 써 없앰" },
  { word: "이익", meaning: "얻는 보람이나 남는 돈" },

  { word: "안전", meaning: "위험이 없는 상태" },
  { word: "위험", meaning: "해를 입을 가능성" },
  { word: "경고", meaning: "조심하라고 미리 알림" },
  { word: "신고", meaning: "일어난 일을 기관에 알림" },
  { word: "경찰", meaning: "질서와 안전을 지키는 사람" },
  { word: "소방", meaning: "불을 끄고 구조하는 일" },
  { word: "구조", meaning: "위험한 사람을 구해 냄" },
  { word: "사고", meaning: "뜻밖에 일어난 나쁜 일" },
  { word: "대피", meaning: "위험한 곳에서 피함" },
  { word: "보호", meaning: "위험에서 지켜 줌" },

  { word: "청소", meaning: "더러운 것을 치우고 깨끗하게 함" },
  { word: "빨래", meaning: "옷이나 천을 씻는 일" },
  { word: "설거지", meaning: "그릇을 씻는 일" },
  { word: "정리", meaning: "흩어진 것을 가지런히 함" },
  { word: "쓰레기", meaning: "버려야 할 물건" },
  { word: "재활용", meaning: "버릴 물건을 다시 이용함" },
  { word: "분리", meaning: "서로 나누어 떼어 놓음" },
  { word: "절약", meaning: "아껴서 적게 씀" },
  { word: "전기", meaning: "빛과 힘을 내는 에너지" },
  { word: "수도꼭지", meaning: "물을 틀고 잠그는 장치" },

  { word: "일기", meaning: "하루의 일을 적은 글" },
  { word: "메모", meaning: "잊지 않으려고 간단히 적음" },
  { word: "계좌", meaning: "은행에서 돈을 관리하는 번호" },
  { word: "예약", meaning: "미리 정해 두고 약속함" },
  { word: "취소", meaning: "정한 일을 없던 것으로 함" },
  { word: "확인", meaning: "틀림이 없는지 살펴봄" },
  { word: "수정", meaning: "잘못된 것을 고침" },
  { word: "완성", meaning: "부족함 없이 다 이룸" },
  { word: "보관", meaning: "물건을 맡아 두거나 간직함" },
  { word: "분실", meaning: "물건을 잃어버림" },

  { word: "출발", meaning: "어떤 곳을 향해 떠남" },
  { word: "도착", meaning: "목적지에 이름" },
  { word: "길잡이", meaning: "길을 안내하는 사람이나 정보" },
  { word: "여권", meaning: "외국에 갈 때 필요한 신분 증명서" },
  { word: "짐", meaning: "옮기거나 가지고 다니는 물건" },
  { word: "숙소", meaning: "여행 중 머무는 곳" },
  { word: "사진첩", meaning: "사진을 모아 둔 책이나 공간" },
  { word: "기념품", meaning: "기억하려고 사거나 남기는 물건" },
  { word: "입장권", meaning: "장소에 들어갈 수 있는 표" },
  { word: "안내문", meaning: "알려 줄 내용을 적은 글" }
];

export const WORDS = words;
